/*
 * generated by Xtext
 */
package org.xtext.enlightenment;

/**
 * Use this class to register components to be used within the IDE.
 */
public class EdjeUiModule extends org.xtext.enlightenment.AbstractEdjeUiModule {

}
