/*
* generated by Xtext
*/
package org.xtext.enlightenment.contentassist;

import org.xtext.enlightenment.contentassist.AbstractEdjeProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class EdjeProposalProvider extends AbstractEdjeProposalProvider {

}
