/*
* generated by Xtext
*/

package org.xtext.enlightenment.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import org.eclipse.xtext.*;

import org.eclipse.xtext.service.GrammarProvider;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class EdjeGrammarAccess implements IGrammarAccess {
	
	
	public class ModelElements implements IParserRuleAccess {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Model");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cIncludesAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cIncludesIncludeParserRuleCall_0_0 = (RuleCall)cIncludesAssignment_0.eContents().get(0);
		private final Assignment cCollectionsAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cCollectionsCollectionsParserRuleCall_1_0 = (RuleCall)cCollectionsAssignment_1.eContents().get(0);
		
		//Model:
		//  includes+=Include* collections+=Collections*;
		public ParserRule getRule() { return rule; }

		//includes+=Include* collections+=Collections*
		public Group getGroup() { return cGroup; }

		//includes+=Include*
		public Assignment getIncludesAssignment_0() { return cIncludesAssignment_0; }

		//Include
		public RuleCall getIncludesIncludeParserRuleCall_0_0() { return cIncludesIncludeParserRuleCall_0_0; }

		//collections+=Collections*
		public Assignment getCollectionsAssignment_1() { return cCollectionsAssignment_1; }

		//Collections
		public RuleCall getCollectionsCollectionsParserRuleCall_1_0() { return cCollectionsCollectionsParserRuleCall_1_0; }
	}

	public class IncludeElements implements IParserRuleAccess {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Include");
		private final Keyword cIncludeKeyword = (Keyword)rule.eContents().get(1);
		
		//Include returns ecore::EString:
		//  "#include";
		public ParserRule getRule() { return rule; }

		//"#include"
		public Keyword getIncludeKeyword() { return cIncludeKeyword; }
	}

	public class DefineElements implements IParserRuleAccess {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Define");
		private final Keyword cDefineKeyword = (Keyword)rule.eContents().get(1);
		
		//Define returns ecore::EString:
		//  "#define";
		public ParserRule getRule() { return rule; }

		//"#define"
		public Keyword getDefineKeyword() { return cDefineKeyword; }
	}

	public class LUA_ScriptElements implements IParserRuleAccess {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "LUA_Script");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLua_scriptKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cContentAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cContentSTRINGTerminalRuleCall_1_0 = (RuleCall)cContentAssignment_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//LUA_Script:
		//  "lua_script {" content=STRING "}";
		public ParserRule getRule() { return rule; }

		//"lua_script {" content=STRING "}"
		public Group getGroup() { return cGroup; }

		//"lua_script {"
		public Keyword getLua_scriptKeyword_0() { return cLua_scriptKeyword_0; }

		//content=STRING
		public Assignment getContentAssignment_1() { return cContentAssignment_1; }

		//STRING
		public RuleCall getContentSTRINGTerminalRuleCall_1_0() { return cContentSTRINGTerminalRuleCall_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_2() { return cRightCurlyBracketKeyword_2; }
	}

	public class CollectionsElements implements IParserRuleAccess {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Collections");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCollectionsKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cGroupsAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cGroupsGroupParserRuleCall_1_0 = (RuleCall)cGroupsAssignment_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//Collections:
		//  "collections {" groups+=Group* "}";
		public ParserRule getRule() { return rule; }

		//"collections {" groups+=Group* "}"
		public Group getGroup() { return cGroup; }

		//"collections {"
		public Keyword getCollectionsKeyword_0() { return cCollectionsKeyword_0; }

		//groups+=Group*
		public Assignment getGroupsAssignment_1() { return cGroupsAssignment_1; }

		//Group
		public RuleCall getGroupsGroupParserRuleCall_1_0() { return cGroupsGroupParserRuleCall_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_2() { return cRightCurlyBracketKeyword_2; }
	}

	public class GroupElements implements IParserRuleAccess {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Group");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cGroupKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cNameKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cNameAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cNameSTRINGTerminalRuleCall_1_1_0 = (RuleCall)cNameAssignment_1_1.eContents().get(0);
		private final Keyword cSemicolonKeyword_1_2 = (Keyword)cGroup_1.eContents().get(2);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cMinKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Group cGroup_2_1 = (Group)cGroup_2.eContents().get(1);
		private final Assignment cMinxAssignment_2_1_0 = (Assignment)cGroup_2_1.eContents().get(0);
		private final RuleCall cMinxINTTerminalRuleCall_2_1_0_0 = (RuleCall)cMinxAssignment_2_1_0.eContents().get(0);
		private final Assignment cMinyAssignment_2_1_1 = (Assignment)cGroup_2_1.eContents().get(1);
		private final RuleCall cMinyINTTerminalRuleCall_2_1_1_0 = (RuleCall)cMinyAssignment_2_1_1.eContents().get(0);
		private final Keyword cSemicolonKeyword_2_2 = (Keyword)cGroup_2.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cPartsKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cPartAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cPartPartParserRuleCall_3_1_0 = (RuleCall)cPartAssignment_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3_2 = (Keyword)cGroup_3.eContents().get(2);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cProgramsKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cProgramAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cProgramProgramParserRuleCall_4_1_0 = (RuleCall)cProgramAssignment_4_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_2 = (Keyword)cGroup_4.eContents().get(2);
		private final Assignment cLua_scriptAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cLua_scriptLUA_ScriptParserRuleCall_5_0 = (RuleCall)cLua_scriptAssignment_5.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Group:
		//  "group {" ("name:" name=STRING ";")? ("min:" (minx=INT miny=INT) ";")? ("parts {" part+=
		//  Part* "}")* ("programs {" program+=Program* "}")* lua_script=LUA_Script? "}";
		public ParserRule getRule() { return rule; }

		//"group {" ("name:" name=STRING ";")? ("min:" (minx=INT miny=INT) ";")? ("parts {" part+=
		//Part* "}")* ("programs {" program+=Program* "}")* lua_script=LUA_Script? "}"
		public Group getGroup() { return cGroup; }

		//"group {"
		public Keyword getGroupKeyword_0() { return cGroupKeyword_0; }

		//("name:" name=STRING ";")?
		public Group getGroup_1() { return cGroup_1; }

		//"name:"
		public Keyword getNameKeyword_1_0() { return cNameKeyword_1_0; }

		//name=STRING
		public Assignment getNameAssignment_1_1() { return cNameAssignment_1_1; }

		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_1_1_0() { return cNameSTRINGTerminalRuleCall_1_1_0; }

		//";"
		public Keyword getSemicolonKeyword_1_2() { return cSemicolonKeyword_1_2; }

		//("min:" (minx=INT miny=INT) ";")?
		public Group getGroup_2() { return cGroup_2; }

		//"min:"
		public Keyword getMinKeyword_2_0() { return cMinKeyword_2_0; }

		//minx=INT miny=INT
		public Group getGroup_2_1() { return cGroup_2_1; }

		//minx=INT
		public Assignment getMinxAssignment_2_1_0() { return cMinxAssignment_2_1_0; }

		//INT
		public RuleCall getMinxINTTerminalRuleCall_2_1_0_0() { return cMinxINTTerminalRuleCall_2_1_0_0; }

		//miny=INT
		public Assignment getMinyAssignment_2_1_1() { return cMinyAssignment_2_1_1; }

		//INT
		public RuleCall getMinyINTTerminalRuleCall_2_1_1_0() { return cMinyINTTerminalRuleCall_2_1_1_0; }

		//";"
		public Keyword getSemicolonKeyword_2_2() { return cSemicolonKeyword_2_2; }

		//("parts {" part+=Part* "}")*
		public Group getGroup_3() { return cGroup_3; }

		//"parts {"
		public Keyword getPartsKeyword_3_0() { return cPartsKeyword_3_0; }

		//part+=Part*
		public Assignment getPartAssignment_3_1() { return cPartAssignment_3_1; }

		//Part
		public RuleCall getPartPartParserRuleCall_3_1_0() { return cPartPartParserRuleCall_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_3_2() { return cRightCurlyBracketKeyword_3_2; }

		//("programs {" program+=Program* "}")*
		public Group getGroup_4() { return cGroup_4; }

		//"programs {"
		public Keyword getProgramsKeyword_4_0() { return cProgramsKeyword_4_0; }

		//program+=Program*
		public Assignment getProgramAssignment_4_1() { return cProgramAssignment_4_1; }

		//Program
		public RuleCall getProgramProgramParserRuleCall_4_1_0() { return cProgramProgramParserRuleCall_4_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_4_2() { return cRightCurlyBracketKeyword_4_2; }

		//lua_script=LUA_Script?
		public Assignment getLua_scriptAssignment_5() { return cLua_scriptAssignment_5; }

		//LUA_Script
		public RuleCall getLua_scriptLUA_ScriptParserRuleCall_5_0() { return cLua_scriptLUA_ScriptParserRuleCall_5_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}

	public class PartElements implements IParserRuleAccess {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Part");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPartKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cNameKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cNameAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cNameSTRINGTerminalRuleCall_1_1_0 = (RuleCall)cNameAssignment_1_1.eContents().get(0);
		private final Keyword cSemicolonKeyword_1_2 = (Keyword)cGroup_1.eContents().get(2);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cMinKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Group cGroup_2_1 = (Group)cGroup_2.eContents().get(1);
		private final Assignment cMinxAssignment_2_1_0 = (Assignment)cGroup_2_1.eContents().get(0);
		private final RuleCall cMinxINTTerminalRuleCall_2_1_0_0 = (RuleCall)cMinxAssignment_2_1_0.eContents().get(0);
		private final Assignment cMinyAssignment_2_1_1 = (Assignment)cGroup_2_1.eContents().get(1);
		private final RuleCall cMinyINTTerminalRuleCall_2_1_1_0 = (RuleCall)cMinyAssignment_2_1_1.eContents().get(0);
		private final Keyword cSemicolonKeyword_2_2 = (Keyword)cGroup_2.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cTypeKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cTypeAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cTypeIDTerminalRuleCall_3_1_0 = (RuleCall)cTypeAssignment_3_1.eContents().get(0);
		private final Keyword cSemicolonKeyword_3_2 = (Keyword)cGroup_3.eContents().get(2);
		private final Assignment cDescriptionsAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cDescriptionsDescriptionParserRuleCall_4_0 = (RuleCall)cDescriptionsAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Part:
		//  "part {" ("name:" name=STRING ";")? ("min:" (minx=INT miny=INT) ";")? ("type:" type=ID ";"
		//  )? descriptions+=Description* "}";
		public ParserRule getRule() { return rule; }

		//"part {" ("name:" name=STRING ";")? ("min:" (minx=INT miny=INT) ";")? ("type:" type=ID ";"
		//)? descriptions+=Description* "}"
		public Group getGroup() { return cGroup; }

		//"part {"
		public Keyword getPartKeyword_0() { return cPartKeyword_0; }

		//("name:" name=STRING ";")?
		public Group getGroup_1() { return cGroup_1; }

		//"name:"
		public Keyword getNameKeyword_1_0() { return cNameKeyword_1_0; }

		//name=STRING
		public Assignment getNameAssignment_1_1() { return cNameAssignment_1_1; }

		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_1_1_0() { return cNameSTRINGTerminalRuleCall_1_1_0; }

		//";"
		public Keyword getSemicolonKeyword_1_2() { return cSemicolonKeyword_1_2; }

		//("min:" (minx=INT miny=INT) ";")?
		public Group getGroup_2() { return cGroup_2; }

		//"min:"
		public Keyword getMinKeyword_2_0() { return cMinKeyword_2_0; }

		//minx=INT miny=INT
		public Group getGroup_2_1() { return cGroup_2_1; }

		//minx=INT
		public Assignment getMinxAssignment_2_1_0() { return cMinxAssignment_2_1_0; }

		//INT
		public RuleCall getMinxINTTerminalRuleCall_2_1_0_0() { return cMinxINTTerminalRuleCall_2_1_0_0; }

		//miny=INT
		public Assignment getMinyAssignment_2_1_1() { return cMinyAssignment_2_1_1; }

		//INT
		public RuleCall getMinyINTTerminalRuleCall_2_1_1_0() { return cMinyINTTerminalRuleCall_2_1_1_0; }

		//";"
		public Keyword getSemicolonKeyword_2_2() { return cSemicolonKeyword_2_2; }

		//("type:" type=ID ";")?
		public Group getGroup_3() { return cGroup_3; }

		//"type:"
		public Keyword getTypeKeyword_3_0() { return cTypeKeyword_3_0; }

		//type=ID
		public Assignment getTypeAssignment_3_1() { return cTypeAssignment_3_1; }

		//ID
		public RuleCall getTypeIDTerminalRuleCall_3_1_0() { return cTypeIDTerminalRuleCall_3_1_0; }

		//";"
		public Keyword getSemicolonKeyword_3_2() { return cSemicolonKeyword_3_2; }

		//descriptions+=Description*
		public Assignment getDescriptionsAssignment_4() { return cDescriptionsAssignment_4; }

		//Description
		public RuleCall getDescriptionsDescriptionParserRuleCall_4_0() { return cDescriptionsDescriptionParserRuleCall_4_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}

	public class DescriptionElements implements IParserRuleAccess {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Description");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cDescriptionKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cRel1Keyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cCoordinatesAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cCoordinatesCoordinatesParserRuleCall_2_0 = (RuleCall)cCoordinatesAssignment_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cRel2Keyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cCoordinatesAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cCoordinatesCoordinatesParserRuleCall_5_0 = (RuleCall)cCoordinatesAssignment_5.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cColorKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Group cGroup_7_1 = (Group)cGroup_7.eContents().get(1);
		private final Assignment cRedAssignment_7_1_0 = (Assignment)cGroup_7_1.eContents().get(0);
		private final RuleCall cRedINTTerminalRuleCall_7_1_0_0 = (RuleCall)cRedAssignment_7_1_0.eContents().get(0);
		private final Assignment cGreenAssignment_7_1_1 = (Assignment)cGroup_7_1.eContents().get(1);
		private final RuleCall cGreenINTTerminalRuleCall_7_1_1_0 = (RuleCall)cGreenAssignment_7_1_1.eContents().get(0);
		private final Assignment cBlueAssignment_7_1_2 = (Assignment)cGroup_7_1.eContents().get(2);
		private final RuleCall cBlueINTTerminalRuleCall_7_1_2_0 = (RuleCall)cBlueAssignment_7_1_2.eContents().get(0);
		private final Assignment cAlphaAssignment_7_1_3 = (Assignment)cGroup_7_1.eContents().get(3);
		private final RuleCall cAlphaINTTerminalRuleCall_7_1_3_0 = (RuleCall)cAlphaAssignment_7_1_3.eContents().get(0);
		private final Keyword cSemicolonKeyword_7_2 = (Keyword)cGroup_7.eContents().get(2);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//Description:
		//  "description {" "rel1 {" coordinates=Coordinates "}" "rel2 {" coordinates=Coordinates
		//  "}" ("color:" (red=INT green=INT blue=INT alpha=INT) ";")? "}";
		public ParserRule getRule() { return rule; }

		//"description {" "rel1 {" coordinates=Coordinates "}" "rel2 {" coordinates=Coordinates
		//"}" ("color:" (red=INT green=INT blue=INT alpha=INT) ";")? "}"
		public Group getGroup() { return cGroup; }

		//"description {"
		public Keyword getDescriptionKeyword_0() { return cDescriptionKeyword_0; }

		//"rel1 {"
		public Keyword getRel1Keyword_1() { return cRel1Keyword_1; }

		//coordinates=Coordinates
		public Assignment getCoordinatesAssignment_2() { return cCoordinatesAssignment_2; }

		//Coordinates
		public RuleCall getCoordinatesCoordinatesParserRuleCall_2_0() { return cCoordinatesCoordinatesParserRuleCall_2_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_3() { return cRightCurlyBracketKeyword_3; }

		//"rel2 {"
		public Keyword getRel2Keyword_4() { return cRel2Keyword_4; }

		//coordinates=Coordinates
		public Assignment getCoordinatesAssignment_5() { return cCoordinatesAssignment_5; }

		//Coordinates
		public RuleCall getCoordinatesCoordinatesParserRuleCall_5_0() { return cCoordinatesCoordinatesParserRuleCall_5_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }

		//("color:" (red=INT green=INT blue=INT alpha=INT) ";")?
		public Group getGroup_7() { return cGroup_7; }

		//"color:"
		public Keyword getColorKeyword_7_0() { return cColorKeyword_7_0; }

		//red=INT green=INT blue=INT alpha=INT
		public Group getGroup_7_1() { return cGroup_7_1; }

		//red=INT
		public Assignment getRedAssignment_7_1_0() { return cRedAssignment_7_1_0; }

		//INT
		public RuleCall getRedINTTerminalRuleCall_7_1_0_0() { return cRedINTTerminalRuleCall_7_1_0_0; }

		//green=INT
		public Assignment getGreenAssignment_7_1_1() { return cGreenAssignment_7_1_1; }

		//INT
		public RuleCall getGreenINTTerminalRuleCall_7_1_1_0() { return cGreenINTTerminalRuleCall_7_1_1_0; }

		//blue=INT
		public Assignment getBlueAssignment_7_1_2() { return cBlueAssignment_7_1_2; }

		//INT
		public RuleCall getBlueINTTerminalRuleCall_7_1_2_0() { return cBlueINTTerminalRuleCall_7_1_2_0; }

		//alpha=INT
		public Assignment getAlphaAssignment_7_1_3() { return cAlphaAssignment_7_1_3; }

		//INT
		public RuleCall getAlphaINTTerminalRuleCall_7_1_3_0() { return cAlphaINTTerminalRuleCall_7_1_3_0; }

		//";"
		public Keyword getSemicolonKeyword_7_2() { return cSemicolonKeyword_7_2; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}

	public class CoordinatesElements implements IParserRuleAccess {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Coordinates");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cGroup.eContents().get(0);
		private final Keyword cAbsoluteKeyword_0_0 = (Keyword)cGroup_0.eContents().get(0);
		private final Group cGroup_0_1 = (Group)cGroup_0.eContents().get(1);
		private final Assignment cXAssignment_0_1_0 = (Assignment)cGroup_0_1.eContents().get(0);
		private final RuleCall cXINTTerminalRuleCall_0_1_0_0 = (RuleCall)cXAssignment_0_1_0.eContents().get(0);
		private final Assignment cYAssignment_0_1_1 = (Assignment)cGroup_0_1.eContents().get(1);
		private final RuleCall cYINTTerminalRuleCall_0_1_1_0 = (RuleCall)cYAssignment_0_1_1.eContents().get(0);
		private final Assignment cWidthAssignment_0_1_2 = (Assignment)cGroup_0_1.eContents().get(2);
		private final RuleCall cWidthINTTerminalRuleCall_0_1_2_0 = (RuleCall)cWidthAssignment_0_1_2.eContents().get(0);
		private final Assignment cHeightAssignment_0_1_3 = (Assignment)cGroup_0_1.eContents().get(3);
		private final RuleCall cHeightINTTerminalRuleCall_0_1_3_0 = (RuleCall)cHeightAssignment_0_1_3.eContents().get(0);
		private final Keyword cSemicolonKeyword_0_2 = (Keyword)cGroup_0.eContents().get(2);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cRelativeKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Group cGroup_1_1 = (Group)cGroup_1.eContents().get(1);
		private final Assignment cXAssignment_1_1_0 = (Assignment)cGroup_1_1.eContents().get(0);
		private final RuleCall cXINTTerminalRuleCall_1_1_0_0 = (RuleCall)cXAssignment_1_1_0.eContents().get(0);
		private final Assignment cYAssignment_1_1_1 = (Assignment)cGroup_1_1.eContents().get(1);
		private final RuleCall cYINTTerminalRuleCall_1_1_1_0 = (RuleCall)cYAssignment_1_1_1.eContents().get(0);
		private final Keyword cSemicolonKeyword_1_2 = (Keyword)cGroup_1.eContents().get(2);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cOffsetKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Group cGroup_2_1 = (Group)cGroup_2.eContents().get(1);
		private final Assignment cXAssignment_2_1_0 = (Assignment)cGroup_2_1.eContents().get(0);
		private final RuleCall cXINTTerminalRuleCall_2_1_0_0 = (RuleCall)cXAssignment_2_1_0.eContents().get(0);
		private final Assignment cYAssignment_2_1_1 = (Assignment)cGroup_2_1.eContents().get(1);
		private final RuleCall cYINTTerminalRuleCall_2_1_1_0 = (RuleCall)cYAssignment_2_1_1.eContents().get(0);
		private final Keyword cSemicolonKeyword_2_2 = (Keyword)cGroup_2.eContents().get(2);
		
		//Coordinates:
		//  ("absolute:" (x=INT y=INT width=INT height=INT) ";")? ("relative:" (x=INT y=INT) ";")? (
		//  "offset:" (x=INT y=INT) ";")?;
		public ParserRule getRule() { return rule; }

		//("absolute:" (x=INT y=INT width=INT height=INT) ";")? ("relative:" (x=INT y=INT) ";")? (
		//"offset:" (x=INT y=INT) ";")?
		public Group getGroup() { return cGroup; }

		//("absolute:" (x=INT y=INT width=INT height=INT) ";")?
		public Group getGroup_0() { return cGroup_0; }

		//"absolute:"
		public Keyword getAbsoluteKeyword_0_0() { return cAbsoluteKeyword_0_0; }

		//x=INT y=INT width=INT height=INT
		public Group getGroup_0_1() { return cGroup_0_1; }

		//x=INT
		public Assignment getXAssignment_0_1_0() { return cXAssignment_0_1_0; }

		//INT
		public RuleCall getXINTTerminalRuleCall_0_1_0_0() { return cXINTTerminalRuleCall_0_1_0_0; }

		//y=INT
		public Assignment getYAssignment_0_1_1() { return cYAssignment_0_1_1; }

		//INT
		public RuleCall getYINTTerminalRuleCall_0_1_1_0() { return cYINTTerminalRuleCall_0_1_1_0; }

		//width=INT
		public Assignment getWidthAssignment_0_1_2() { return cWidthAssignment_0_1_2; }

		//INT
		public RuleCall getWidthINTTerminalRuleCall_0_1_2_0() { return cWidthINTTerminalRuleCall_0_1_2_0; }

		//height=INT
		public Assignment getHeightAssignment_0_1_3() { return cHeightAssignment_0_1_3; }

		//INT
		public RuleCall getHeightINTTerminalRuleCall_0_1_3_0() { return cHeightINTTerminalRuleCall_0_1_3_0; }

		//";"
		public Keyword getSemicolonKeyword_0_2() { return cSemicolonKeyword_0_2; }

		//("relative:" (x=INT y=INT) ";")?
		public Group getGroup_1() { return cGroup_1; }

		//"relative:"
		public Keyword getRelativeKeyword_1_0() { return cRelativeKeyword_1_0; }

		//x=INT y=INT
		public Group getGroup_1_1() { return cGroup_1_1; }

		//x=INT
		public Assignment getXAssignment_1_1_0() { return cXAssignment_1_1_0; }

		//INT
		public RuleCall getXINTTerminalRuleCall_1_1_0_0() { return cXINTTerminalRuleCall_1_1_0_0; }

		//y=INT
		public Assignment getYAssignment_1_1_1() { return cYAssignment_1_1_1; }

		//INT
		public RuleCall getYINTTerminalRuleCall_1_1_1_0() { return cYINTTerminalRuleCall_1_1_1_0; }

		//";"
		public Keyword getSemicolonKeyword_1_2() { return cSemicolonKeyword_1_2; }

		//("offset:" (x=INT y=INT) ";")?
		public Group getGroup_2() { return cGroup_2; }

		//"offset:"
		public Keyword getOffsetKeyword_2_0() { return cOffsetKeyword_2_0; }

		//x=INT y=INT
		public Group getGroup_2_1() { return cGroup_2_1; }

		//x=INT
		public Assignment getXAssignment_2_1_0() { return cXAssignment_2_1_0; }

		//INT
		public RuleCall getXINTTerminalRuleCall_2_1_0_0() { return cXINTTerminalRuleCall_2_1_0_0; }

		//y=INT
		public Assignment getYAssignment_2_1_1() { return cYAssignment_2_1_1; }

		//INT
		public RuleCall getYINTTerminalRuleCall_2_1_1_0() { return cYINTTerminalRuleCall_2_1_1_0; }

		//";"
		public Keyword getSemicolonKeyword_2_2() { return cSemicolonKeyword_2_2; }
	}

	public class ProgramsElements implements IParserRuleAccess {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Programs");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cProgramsKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cProgramAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cProgramProgramParserRuleCall_1_0 = (RuleCall)cProgramAssignment_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//Programs:
		//  "programs {" program+=Program* "}";
		public ParserRule getRule() { return rule; }

		//"programs {" program+=Program* "}"
		public Group getGroup() { return cGroup; }

		//"programs {"
		public Keyword getProgramsKeyword_0() { return cProgramsKeyword_0; }

		//program+=Program*
		public Assignment getProgramAssignment_1() { return cProgramAssignment_1; }

		//Program
		public RuleCall getProgramProgramParserRuleCall_1_0() { return cProgramProgramParserRuleCall_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_2() { return cRightCurlyBracketKeyword_2; }
	}

	public class ProgramElements implements IParserRuleAccess {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Program");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cProgramKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cNameKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cNameAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cNameSTRINGTerminalRuleCall_1_1_0 = (RuleCall)cNameAssignment_1_1.eContents().get(0);
		private final Keyword cSemicolonKeyword_1_2 = (Keyword)cGroup_1.eContents().get(2);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cSignalKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cSignalAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cSignalSTRINGTerminalRuleCall_2_1_0 = (RuleCall)cSignalAssignment_2_1.eContents().get(0);
		private final Keyword cSemicolonKeyword_2_2 = (Keyword)cGroup_2.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cSourceKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cSourceAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cSourceSTRINGTerminalRuleCall_3_1_0 = (RuleCall)cSourceAssignment_3_1.eContents().get(0);
		private final Keyword cSemicolonKeyword_3_2 = (Keyword)cGroup_3.eContents().get(2);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cActionKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cActionAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cActionActionParserRuleCall_4_1_0 = (RuleCall)cActionAssignment_4_1.eContents().get(0);
		private final Assignment cLua_scriptAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cLua_scriptLUA_ScriptParserRuleCall_5_0 = (RuleCall)cLua_scriptAssignment_5.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Program:
		//  "program {" ("name:" name=STRING ";") ("signal:" signal=STRING ";") ("source:" source=
		//  STRING ";") ("action:" action=Action)? lua_script=LUA_Script? "}";
		public ParserRule getRule() { return rule; }

		//"program {" ("name:" name=STRING ";") ("signal:" signal=STRING ";") ("source:" source=
		//STRING ";") ("action:" action=Action)? lua_script=LUA_Script? "}"
		public Group getGroup() { return cGroup; }

		//"program {"
		public Keyword getProgramKeyword_0() { return cProgramKeyword_0; }

		//"name:" name=STRING ";"
		public Group getGroup_1() { return cGroup_1; }

		//"name:"
		public Keyword getNameKeyword_1_0() { return cNameKeyword_1_0; }

		//name=STRING
		public Assignment getNameAssignment_1_1() { return cNameAssignment_1_1; }

		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_1_1_0() { return cNameSTRINGTerminalRuleCall_1_1_0; }

		//";"
		public Keyword getSemicolonKeyword_1_2() { return cSemicolonKeyword_1_2; }

		//"signal:" signal=STRING ";"
		public Group getGroup_2() { return cGroup_2; }

		//"signal:"
		public Keyword getSignalKeyword_2_0() { return cSignalKeyword_2_0; }

		//signal=STRING
		public Assignment getSignalAssignment_2_1() { return cSignalAssignment_2_1; }

		//STRING
		public RuleCall getSignalSTRINGTerminalRuleCall_2_1_0() { return cSignalSTRINGTerminalRuleCall_2_1_0; }

		//";"
		public Keyword getSemicolonKeyword_2_2() { return cSemicolonKeyword_2_2; }

		//"source:" source=STRING ";"
		public Group getGroup_3() { return cGroup_3; }

		//"source:"
		public Keyword getSourceKeyword_3_0() { return cSourceKeyword_3_0; }

		//source=STRING
		public Assignment getSourceAssignment_3_1() { return cSourceAssignment_3_1; }

		//STRING
		public RuleCall getSourceSTRINGTerminalRuleCall_3_1_0() { return cSourceSTRINGTerminalRuleCall_3_1_0; }

		//";"
		public Keyword getSemicolonKeyword_3_2() { return cSemicolonKeyword_3_2; }

		//("action:" action=Action)?
		public Group getGroup_4() { return cGroup_4; }

		//"action:"
		public Keyword getActionKeyword_4_0() { return cActionKeyword_4_0; }

		//action=Action
		public Assignment getActionAssignment_4_1() { return cActionAssignment_4_1; }

		//Action
		public RuleCall getActionActionParserRuleCall_4_1_0() { return cActionActionParserRuleCall_4_1_0; }

		//lua_script=LUA_Script?
		public Assignment getLua_scriptAssignment_5() { return cLua_scriptAssignment_5; }

		//LUA_Script
		public RuleCall getLua_scriptLUA_ScriptParserRuleCall_5_0() { return cLua_scriptLUA_ScriptParserRuleCall_5_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}

	public class ActionElements implements IParserRuleAccess {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Action");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Assignment cParamsAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cParamsSTRINGTerminalRuleCall_1_0 = (RuleCall)cParamsAssignment_1.eContents().get(0);
		private final Keyword cSemicolonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//Action:
		//  name=ID params+=STRING* ";";
		public ParserRule getRule() { return rule; }

		//name=ID params+=STRING* ";"
		public Group getGroup() { return cGroup; }

		//name=ID
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0() { return cNameIDTerminalRuleCall_0_0; }

		//params+=STRING*
		public Assignment getParamsAssignment_1() { return cParamsAssignment_1; }

		//STRING
		public RuleCall getParamsSTRINGTerminalRuleCall_1_0() { return cParamsSTRINGTerminalRuleCall_1_0; }

		//";"
		public Keyword getSemicolonKeyword_2() { return cSemicolonKeyword_2; }
	}
	
	
	private ModelElements pModel;
	private IncludeElements pInclude;
	private DefineElements pDefine;
	private LUA_ScriptElements pLUA_Script;
	private CollectionsElements pCollections;
	private GroupElements pGroup;
	private PartElements pPart;
	private DescriptionElements pDescription;
	private CoordinatesElements pCoordinates;
	private ProgramsElements pPrograms;
	private ProgramElements pProgram;
	private ActionElements pAction;
	
	private final GrammarProvider grammarProvider;

	private TerminalsGrammarAccess gaTerminals;

	@Inject
	public EdjeGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammarProvider = grammarProvider;
		this.gaTerminals = gaTerminals;
	}
	
	public Grammar getGrammar() {	
		return grammarProvider.getGrammar(this);
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Model:
	//  includes+=Include* collections+=Collections*;
	public ModelElements getModelAccess() {
		return (pModel != null) ? pModel : (pModel = new ModelElements());
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}

	//Include returns ecore::EString:
	//  "#include";
	public IncludeElements getIncludeAccess() {
		return (pInclude != null) ? pInclude : (pInclude = new IncludeElements());
	}
	
	public ParserRule getIncludeRule() {
		return getIncludeAccess().getRule();
	}

	//Define returns ecore::EString:
	//  "#define";
	public DefineElements getDefineAccess() {
		return (pDefine != null) ? pDefine : (pDefine = new DefineElements());
	}
	
	public ParserRule getDefineRule() {
		return getDefineAccess().getRule();
	}

	//LUA_Script:
	//  "lua_script {" content=STRING "}";
	public LUA_ScriptElements getLUA_ScriptAccess() {
		return (pLUA_Script != null) ? pLUA_Script : (pLUA_Script = new LUA_ScriptElements());
	}
	
	public ParserRule getLUA_ScriptRule() {
		return getLUA_ScriptAccess().getRule();
	}

	//Collections:
	//  "collections {" groups+=Group* "}";
	public CollectionsElements getCollectionsAccess() {
		return (pCollections != null) ? pCollections : (pCollections = new CollectionsElements());
	}
	
	public ParserRule getCollectionsRule() {
		return getCollectionsAccess().getRule();
	}

	//Group:
	//  "group {" ("name:" name=STRING ";")? ("min:" (minx=INT miny=INT) ";")? ("parts {" part+=
	//  Part* "}")* ("programs {" program+=Program* "}")* lua_script=LUA_Script? "}";
	public GroupElements getGroupAccess() {
		return (pGroup != null) ? pGroup : (pGroup = new GroupElements());
	}
	
	public ParserRule getGroupRule() {
		return getGroupAccess().getRule();
	}

	//Part:
	//  "part {" ("name:" name=STRING ";")? ("min:" (minx=INT miny=INT) ";")? ("type:" type=ID ";"
	//  )? descriptions+=Description* "}";
	public PartElements getPartAccess() {
		return (pPart != null) ? pPart : (pPart = new PartElements());
	}
	
	public ParserRule getPartRule() {
		return getPartAccess().getRule();
	}

	//Description:
	//  "description {" "rel1 {" coordinates=Coordinates "}" "rel2 {" coordinates=Coordinates
	//  "}" ("color:" (red=INT green=INT blue=INT alpha=INT) ";")? "}";
	public DescriptionElements getDescriptionAccess() {
		return (pDescription != null) ? pDescription : (pDescription = new DescriptionElements());
	}
	
	public ParserRule getDescriptionRule() {
		return getDescriptionAccess().getRule();
	}

	//Coordinates:
	//  ("absolute:" (x=INT y=INT width=INT height=INT) ";")? ("relative:" (x=INT y=INT) ";")? (
	//  "offset:" (x=INT y=INT) ";")?;
	public CoordinatesElements getCoordinatesAccess() {
		return (pCoordinates != null) ? pCoordinates : (pCoordinates = new CoordinatesElements());
	}
	
	public ParserRule getCoordinatesRule() {
		return getCoordinatesAccess().getRule();
	}

	//Programs:
	//  "programs {" program+=Program* "}";
	public ProgramsElements getProgramsAccess() {
		return (pPrograms != null) ? pPrograms : (pPrograms = new ProgramsElements());
	}
	
	public ParserRule getProgramsRule() {
		return getProgramsAccess().getRule();
	}

	//Program:
	//  "program {" ("name:" name=STRING ";") ("signal:" signal=STRING ";") ("source:" source=
	//  STRING ";") ("action:" action=Action)? lua_script=LUA_Script? "}";
	public ProgramElements getProgramAccess() {
		return (pProgram != null) ? pProgram : (pProgram = new ProgramElements());
	}
	
	public ParserRule getProgramRule() {
		return getProgramAccess().getRule();
	}

	//Action:
	//  name=ID params+=STRING* ";";
	public ActionElements getActionAccess() {
		return (pAction != null) ? pAction : (pAction = new ActionElements());
	}
	
	public ParserRule getActionRule() {
		return getActionAccess().getRule();
	}

	//terminal ID:
	//  "^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//  "0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//  "\"" ("\\" ("b" | "t" | "n" | "f" | "r" | "\"" | "\'" | "\\") | !("\\" | "\""))* "\"" | "\'" ("\\" ("b" |
	//  "t" | "n" | "f" | "r" | "\"" | "\'" | "\\") | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//  "/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//  "//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//  (" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//  .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
